/** All option files that belong to the current behavior have to be included by this file. */

#include "Options/Soccer.h"

#include "Options/HeadControl/HeadControl.h"

#include "Options/GameControl/HandleGameState.h"
#include "Options/GameControl/HandlePenaltyState.h"
#include "Options/GameControl/PlayingState.h"
#include "Options/GameControl/ReadyState.h"

#include "Options/HeadControl/HeadSweep.h"
#include "Options/HeadControl/LookForward.h"
#include "Options/HeadControl/TrackBall.h"
#include "Options/HeadControl/TrackBallModel.h"
#include "Options/HeadControl/TrackBallSweep.h"
#include "Options/HeadControl/TrackBallSweepBallModel.h"
#include "Options/HeadControl/SearchBall.h"
#include "Options/HeadControl/SearchForBall.h"
#include "Options/HeadControl/TrackPoint.h"

#include "Options/Output/Activity.h"
#include "Options/Output/Annotation.h"
#include "Options/Output/HeadMotionRequest/SetHeadPanTilt.h"
#include "Options/Output/MotionRequest/InWalkKick.h"
#include "Options/Output/MotionRequest/TurnInPlace.h"
#include "Options/Output/MotionRequest/AlignForKick.h"
#include "Options/Output/MotionRequest/KickFar.h"
#include "Options/Output/MotionRequest/SpecialAction.h"
#include "Options/Output/MotionRequest/Stand.h"
#include "Options/Output/MotionRequest/MakeTurn.h"
#include "Options/Output/MotionRequest/ArmInBack.h"
#include "Options/Output/MotionRequest/WalkAtAbsoluteSpeed.h"
#include "Options/Output/MotionRequest/WalkAtRelativeSpeed.h"
#include "Options/Output/MotionRequest/WalkToBall.h"
#include "Options/Output/MotionRequest/WalkToTarget.h"
#include "Options/Output/MotionRequest/GetUpEngine.h"
#include "Options/Output/MotionRequest/MovePlayerToStartPosition.h"
#include "Options/Output/MotionRequest/Pass.h"
#include "Options/Output/MotionRequest/KickWithPosition.h"
#include "Options/Output/MotionRequest/Wall.h"
#include "Options/Output/MotionRequest/WalkToSafeDistance.h"

//#include "Options/Output/MotionRequest/Sumo.h"

#include "Options/Output/PlaySound.h"

#include "Options/Roles/Striker.h"
#include "Options/Roles/Keeper.h"
#include "Options/Roles/RightDefender.h"
#include "Options/Roles/LeftDefender.h"
#include "Options/Roles/Defender.h"
#include "Options/Roles/Supporter.h"

#include "Options/GamePhases/PenaltyShoot.h"
#include "Options/GamePhases/OffensivePenaltyShoot.h"
#include "Options/GamePhases/DefensivePenaltyShoot.h"
#include "Options/GamePhases/GoalKick.h"
#include "Options/GamePhases/OffensiveGoalKick.h"
#include "Options/GamePhases/DefensiveGoalKick.h"
#include "Options/GamePhases/PushingFreeKick.h"
#include "Options/GamePhases/OffensivePushingFreeKick.h"
#include "Options/GamePhases/DefensivePushingFreeKick.h"
#include "Options/GamePhases/CornerKick.h"
#include "Options/GamePhases/OffensiveCornerKick.h"
#include "Options/GamePhases/DefensiveCornerKick.h"
#include "Options/GamePhases/KickIn.h"
#include "Options/GamePhases/OffensiveKickIn.h"
#include "Options/GamePhases/DefensiveKickIn.h"

#include "Options/Skills/GetUp.h"
#include "Options/Skills/Dribble.h"
#include "Options/Skills/SearchBallTriangle.h"

#include "Options/DemoOptions/Demo.h"
#include "Options/DemoOptions/Waving.h"

#include "Options/Tactic/HandleTeamTactic.h"

#include "Options/Tools/ButtonPressedAndReleased.h"
#include "Options/Tools/ButtonPressed.h"