#pragma once

#define YOLO_PLAYER_INPUT_CHANNELS 1

#define YOLO_PLAYER_INPUT_HEIGHT 60
#define YOLO_PLAYER_INPUT_WIDTH 80
#define YOLO_PLAYER_INPUT_HEIGHT_STEP (YOLO_PLAYER_INPUT_WIDTH * YOLO_PLAYER_INPUT_CHANNELS)
#define YOLO_PLAYER_INPUT_SIZE (YOLO_PLAYER_INPUT_HEIGHT * YOLO_PLAYER_INPUT_HEIGHT_STEP)

#define YOLO_PLAYER_OUTPUT_HEIGHT 8
#define YOLO_PLAYER_OUTPUT_WIDTH 10
#define YOLO_PLAYER_ANCHORS_NUMBER 6
#define YOLO_PLAYER_OUTPUT_CHANNELS (YOLO_PLAYER_ANCHORS_NUMBER + 5)
#define YOLO_PLAYER_OUTPUT_HEIGHT_STEP (YOLO_PLAYER_OUTPUT_WIDTH * YOLO_PLAYER_OUTPUT_CHANNELS)
#define YOLO_PLAYER_OUTPUT_SIZE (YOLO_PLAYER_OUTPUT_HEIGHT * YOLO_PLAYER_OUTPUT_HEIGHT_STEP)
#define YOLO_PLAYER_ANCHORS_WIDTH(index) (int[YOLO_PLAYER_ANCHORS_NUMBER/2]) {45, 128, 261}[index]
#define YOLO_PLAYER_ANCHORS_HEIGHT(index) (int[YOLO_PLAYER_ANCHORS_NUMBER/2]) {65, 180, 341}[index]
