#pragma once

#define YOLO_BALL_INPUT_CHANNELS 3

#ifdef TARGET_ROBOT

#define YOLO_BALL_LOWER_INPUT_HEIGHT 60
#define YOLO_BALL_LOWER_INPUT_WIDTH 80
#define YOLO_BALL_LOWER_INPUT_HEIGHT_STEP (YOLO_BALL_LOWER_INPUT_WIDTH * YOLO_BALL_INPUT_CHANNELS)
#define YOLO_BALL_LOWER_INPUT_SIZE (YOLO_BALL_LOWER_INPUT_HEIGHT * YOLO_BALL_LOWER_INPUT_HEIGHT_STEP)

#define YOLO_BALL_LOWER_OUTPUT_HEIGHT 7
#define YOLO_BALL_LOWER_OUTPUT_WIDTH 10
#define YOLO_BALL_LOWER_ANCHORS_NUMBER 4
#define YOLO_BALL_LOWER_OUTPUT_CHANNELS (YOLO_BALL_LOWER_ANCHORS_NUMBER + 5)
#define YOLO_BALL_LOWER_OUTPUT_HEIGHT_STEP (YOLO_BALL_LOWER_OUTPUT_WIDTH * YOLO_BALL_LOWER_OUTPUT_CHANNELS)
#define YOLO_BALL_LOWER_OUTPUT_SIZE (YOLO_BALL_LOWER_OUTPUT_HEIGHT * YOLO_BALL_LOWER_OUTPUT_HEIGHT_STEP)
#define YOLO_BALL_LOWER_ANCHORS(index) (float[YOLO_BALL_LOWER_ANCHORS_NUMBER]) {0.101536f, 0.117589f, 0.129282f, 0.143436f}[index]

#define YOLO_BALL_LOWER_MIN_CONFIDENCE 0.4f
#define YOLO_BALL_LOWER_MIN_GUESSED_CONFIDENCE 0.3f


#define YOLO_BALL_UPPER_INPUT_HEIGHT 120
#define YOLO_BALL_UPPER_INPUT_WIDTH 160
#define YOLO_BALL_UPPER_INPUT_HEIGHT_STEP (YOLO_BALL_UPPER_INPUT_WIDTH * YOLO_BALL_INPUT_CHANNELS)
#define YOLO_BALL_UPPER_INPUT_SIZE (YOLO_BALL_UPPER_INPUT_HEIGHT * YOLO_BALL_UPPER_INPUT_HEIGHT_STEP)

#define YOLO_BALL_UPPER_OUTPUT_HEIGHT 15
#define YOLO_BALL_UPPER_OUTPUT_WIDTH 20
#define YOLO_BALL_UPPER_ANCHORS_NUMBER 4
#define YOLO_BALL_UPPER_OUTPUT_CHANNELS (YOLO_BALL_UPPER_ANCHORS_NUMBER + 5)
#define YOLO_BALL_UPPER_OUTPUT_HEIGHT_STEP (YOLO_BALL_UPPER_OUTPUT_WIDTH * YOLO_BALL_UPPER_OUTPUT_CHANNELS)
#define YOLO_BALL_UPPER_OUTPUT_SIZE (YOLO_BALL_UPPER_OUTPUT_HEIGHT * YOLO_BALL_UPPER_OUTPUT_HEIGHT_STEP)
#define YOLO_BALL_UPPER_ANCHORS(index) (float[YOLO_BALL_UPPER_ANCHORS_NUMBER]) {0.0297f, 0.05628f, 0.080817f, 0.12251f}[index]

#define YOLO_BALL_UPPER_MIN_CONFIDENCE 0.55f
#define YOLO_BALL_UPPER_MIN_GUESSED_CONFIDENCE 0.5f

#define get_yolo_ball_input_height(is_upper) (is_upper ? YOLO_BALL_UPPER_INPUT_HEIGHT : YOLO_BALL_LOWER_INPUT_HEIGHT)
#define get_yolo_ball_input_width(is_upper) (is_upper ? YOLO_BALL_UPPER_INPUT_WIDTH : YOLO_BALL_LOWER_INPUT_WIDTH)
#define get_yolo_ball_input_height_step(is_upper) (is_upper ? YOLO_BALL_UPPER_INPUT_HEIGHT_STEP : YOLO_BALL_LOWER_INPUT_HEIGHT_STEP)
#define get_yolo_ball_input_size(is_upper) (is_upper ? YOLO_BALL_UPPER_INPUT_SIZE : YOLO_BALL_LOWER_INPUT_SIZE)

#define get_yolo_ball_output_height(is_upper) (is_upper ? YOLO_BALL_UPPER_OUTPUT_HEIGHT : YOLO_BALL_LOWER_OUTPUT_HEIGHT)
#define get_yolo_ball_output_width(is_upper) (is_upper ? YOLO_BALL_UPPER_OUTPUT_WIDTH : YOLO_BALL_LOWER_OUTPUT_WIDTH)
#define get_yolo_ball_output_anchors_number(is_upper) (is_upper ? YOLO_BALL_UPPER_ANCHORS_NUMBER : YOLO_BALL_LOWER_ANCHORS_NUMBER)

#define get_yolo_ball_output_channels(is_upper) (is_upper ? YOLO_BALL_UPPER_OUTPUT_CHANNELS : YOLO_BALL_LOWER_OUTPUT_CHANNELS)
#define get_yolo_ball_output_height_step(is_upper) (is_upper ? YOLO_BALL_UPPER_OUTPUT_HEIGHT_STEP : YOLO_BALL_LOWER_OUTPUT_HEIGHT_STEP)
#define get_yolo_ball_output_size(is_upper) (is_upper ? YOLO_BALL_UPPER_OUTPUT_SIZE : YOLO_BALL_LOWER_OUTPUT_SIZE)
#define get_yolo_ball_output_anchors(is_upper, index) (is_upper ? YOLO_BALL_UPPER_ANCHORS(index) : YOLO_BALL_LOWER_ANCHORS(index))

#define get_min_ball_confidence(is_upper) (is_upper ? YOLO_BALL_UPPER_MIN_CONFIDENCE : YOLO_BALL_LOWER_MIN_CONFIDENCE)
#define get_min_ball_guessed_confidence(is_upper) (is_upper ? YOLO_BALL_UPPER_MIN_GUESSED_CONFIDENCE : YOLO_BALL_LOWER_MIN_GUESSED_CONFIDENCE)

#else

#define YOLO_BALL_LOWER_INPUT_HEIGHT 60
#define YOLO_BALL_LOWER_INPUT_WIDTH 80
#define YOLO_BALL_LOWER_INPUT_HEIGHT_STEP (YOLO_BALL_LOWER_INPUT_WIDTH * YOLO_BALL_INPUT_CHANNELS)
#define YOLO_BALL_LOWER_INPUT_SIZE (YOLO_BALL_LOWER_INPUT_HEIGHT * YOLO_BALL_LOWER_INPUT_HEIGHT_STEP)

#define YOLO_BALL_LOWER_OUTPUT_HEIGHT 7
#define YOLO_BALL_LOWER_OUTPUT_WIDTH 10
#define YOLO_BALL_LOWER_ANCHORS_NUMBER 4
#define YOLO_BALL_LOWER_OUTPUT_CHANNELS (YOLO_BALL_LOWER_ANCHORS_NUMBER + 5)
#define YOLO_BALL_LOWER_OUTPUT_HEIGHT_STEP (YOLO_BALL_LOWER_OUTPUT_WIDTH * YOLO_BALL_LOWER_OUTPUT_CHANNELS)
#define YOLO_BALL_LOWER_OUTPUT_SIZE (YOLO_BALL_LOWER_OUTPUT_HEIGHT * YOLO_BALL_LOWER_OUTPUT_HEIGHT_STEP)
#define YOLO_BALL_LOWER_ANCHORS(index) (float[YOLO_BALL_LOWER_ANCHORS_NUMBER]) {0.101536f, 0.117589f, 0.129282f, 0.143436f}[index]

#define YOLO_BALL_LOWER_MIN_CONFIDENCE 0.5f
#define YOLO_BALL_LOWER_MIN_GUESSED_CONFIDENCE 0.35f


#define YOLO_BALL_UPPER_INPUT_HEIGHT 120
#define YOLO_BALL_UPPER_INPUT_WIDTH 160
#define YOLO_BALL_UPPER_INPUT_HEIGHT_STEP (YOLO_BALL_UPPER_INPUT_WIDTH * YOLO_BALL_INPUT_CHANNELS)
#define YOLO_BALL_UPPER_INPUT_SIZE (YOLO_BALL_UPPER_INPUT_HEIGHT * YOLO_BALL_UPPER_INPUT_HEIGHT_STEP)

#define YOLO_BALL_UPPER_OUTPUT_HEIGHT 15
#define YOLO_BALL_UPPER_OUTPUT_WIDTH 20
#define YOLO_BALL_UPPER_ANCHORS_NUMBER 4
#define YOLO_BALL_UPPER_OUTPUT_CHANNELS (YOLO_BALL_UPPER_ANCHORS_NUMBER + 5)
#define YOLO_BALL_UPPER_OUTPUT_HEIGHT_STEP (YOLO_BALL_UPPER_OUTPUT_WIDTH * YOLO_BALL_UPPER_OUTPUT_CHANNELS)
#define YOLO_BALL_UPPER_OUTPUT_SIZE (YOLO_BALL_UPPER_OUTPUT_HEIGHT * YOLO_BALL_UPPER_OUTPUT_HEIGHT_STEP)
#define YOLO_BALL_UPPER_ANCHORS(index) (float[YOLO_BALL_UPPER_ANCHORS_NUMBER]) {0.0297f, 0.05628f, 0.080817f, 0.12251f}[index]

#define YOLO_BALL_UPPER_MIN_CONFIDENCE 0.56f
#define YOLO_BALL_UPPER_MIN_GUESSED_CONFIDENCE 0.35f

#define get_yolo_ball_input_height(is_upper) (is_upper ? YOLO_BALL_UPPER_INPUT_HEIGHT : YOLO_BALL_LOWER_INPUT_HEIGHT)
#define get_yolo_ball_input_width(is_upper) (is_upper ? YOLO_BALL_UPPER_INPUT_WIDTH : YOLO_BALL_LOWER_INPUT_WIDTH)
#define get_yolo_ball_input_height_step(is_upper) (is_upper ? YOLO_BALL_UPPER_INPUT_HEIGHT_STEP : YOLO_BALL_LOWER_INPUT_HEIGHT_STEP)
#define get_yolo_ball_input_size(is_upper) (is_upper ? YOLO_BALL_UPPER_INPUT_SIZE : YOLO_BALL_LOWER_INPUT_SIZE)

#define get_yolo_ball_output_height(is_upper) (is_upper ? YOLO_BALL_UPPER_OUTPUT_HEIGHT : YOLO_BALL_LOWER_OUTPUT_HEIGHT)
#define get_yolo_ball_output_width(is_upper) (is_upper ? YOLO_BALL_UPPER_OUTPUT_WIDTH : YOLO_BALL_LOWER_OUTPUT_WIDTH)
#define get_yolo_ball_output_anchors_number(is_upper) (is_upper ? YOLO_BALL_UPPER_ANCHORS_NUMBER : YOLO_BALL_LOWER_ANCHORS_NUMBER)

#define get_yolo_ball_output_channels(is_upper) (is_upper ? YOLO_BALL_UPPER_OUTPUT_CHANNELS : YOLO_BALL_LOWER_OUTPUT_CHANNELS)
#define get_yolo_ball_output_height_step(is_upper) (is_upper ? YOLO_BALL_UPPER_OUTPUT_HEIGHT_STEP : YOLO_BALL_LOWER_OUTPUT_HEIGHT_STEP)
#define get_yolo_ball_output_size(is_upper) (is_upper ? YOLO_BALL_UPPER_OUTPUT_SIZE : YOLO_BALL_LOWER_OUTPUT_SIZE)
#define get_yolo_ball_output_anchors(is_upper, index) (is_upper ? YOLO_BALL_UPPER_ANCHORS(index) : YOLO_BALL_LOWER_ANCHORS(index))

#define get_min_ball_confidence(is_upper) (is_upper ? YOLO_BALL_UPPER_MIN_CONFIDENCE : YOLO_BALL_LOWER_MIN_CONFIDENCE)
#define get_min_ball_guessed_confidence(is_upper) (is_upper ? YOLO_BALL_UPPER_MIN_GUESSED_CONFIDENCE : YOLO_BALL_LOWER_MIN_GUESSED_CONFIDENCE)

#endif

#define get_yolo_ball_original_width(is_upper) (is_upper ? 320.f : 160.f)